### ISSUE TITLE
Will he be able to boot the windows arm in the future?

### ISSUE THREAD

**Issue by XperfectTR** [andreiw/RaspberryPiPkg#10]
Will he be able to boot the windows arm in the future?

**Comment by andreiw** [comment]
Short answer is - no. Windows for Pi is 32-bit only and this is 64-bit firmware.

Long answer is:
- Yes, if MS releases an Arm64 build for RPi3, with the right HAL and drivers.
- Yes, if I write a 32-on-64 UEFI shim.

**Comment by andreiw** [comment]
See for a positive answer - https://github.com/andreiw/RaspberryPiPkg/issues/12

![img_4684 3](https://user-images.githubusercontent.com/732523/39093056-166b80dc-45e7-11e8-9886-202bc85c5507.JPG)

Looks like the crucial RPi3 bits are already baked-in, but drivers are missing (USB being the painful one).
