### ISSUE TITLE
Translate into zh_CN / zh_HK / zh_TW

### ISSUE THREAD

**Issue by 740291272** [andreiw/RaspberryPiPkg#11]
yee，That‘s a very useful tool.
I want to translate it into Chinese,How can i do it.
thanks for repy.

**Comment by andreiw** [comment]
http://download2.nust.na/pub4/sourceforge/e/ed/edk2/General%20Documentation/EDKII%20Module%20Writer_s%20Guide_0_7.pdf
http://wiki.phoenix.com/wiki/index.php/HII

https://uefi.blogspot.com/2009/09/uefi-hii-part-1.html
https://uefi.blogspot.com/2009/09/uefi-hii-part-2.html
https://uefi.blogspot.com/2009/10/uefi-hii-part-3.html
https://uefi.blogspot.com/2009/10/uefi-hii-part-4-strings.html
https://uefi.blogspot.com/2009/10/uefi-hii-part-5-strings-api.html
https://uefi.blogspot.com/2009/11/uefi-hii-part-6-simple-fonts.html
https://uefi.blogspot.com/2009/12/uefi-hii-part-7-character-encoding.html
https://uefi.blogspot.com/2010/01/uefi-hii-part-8-proportional-fonts.html
https://uefi.blogspot.com/2010/01/uefi-hii-part-9-font-package-encoding.html
https://uefi.blogspot.com/2010/01/uefi-hii-part-10-images.html
https://uefi.blogspot.com/2010/02/uefi-hii-part-11-image-package-encoding.html
