### ISSUE TITLE
WoA won't boot

### ISSUE THREAD

**Issue by himike123** [andreiw/RaspberryPiPkg#114]
Im having a issue with WoA not booting  it's stays on the screen were it says "Exiting UEFI and booting OS kernel" in trying to boot from USB since my desktop does not have a SD card reader, I would try to go in the bootloader and change boot option but it won't show my USB all it shows is "port 1 port 2 port 3 port 4" any help but be grateful

**Comment by andreiw** [comment]
You’re using a really old uefi firmware build. For sure. Use the latest.

What windows build are you booting? Did you change hypdxe settings to boot in EL1 instead of EL2?

A

**Comment by himike123** [comment]
Thanks for the fast reply, I'll try changing the hypdxe and install the latest UEFI, also may you please link the latest UEFI software for me please?

**Comment by andreiw** [comment]
https://github.com/andreiw/RaspberryPiPkg/tree/master/Binary/prebuilt/2019Jan16-GCC5/RELEASE
