### ISSUE TITLE
Not able to go back to broadcom driver in boot

### ISSUE THREAD

**Issue by zopit** [andreiw/RaspberryPiPkg#116]
I installed everthing correct but after the complete install of windows not able to go into the boot menu to change the sd card driver back to broadcom because time is like milisecond to press esc or any key and it start the window process and now the its slow because of the driver pls help ??

**Comment by BenNottelling** [comment]
Just spam the escape key..

**Comment by zopit** [comment]
Already tried the every comination not able to get to the boot menu any other hint ?

**Comment by BenNottelling** [comment]
There is no combination, it's a just the escape key
I've done this all the time, so I'm not sure what else might be going on

**Comment by mariobalanica** [comment]
Type "exit" at the EFI shell.

**Comment by zopit** [comment]
I think i hve to install comletely one more time and increase the time of boot menu from 5 to 10 sec :unamused:

**Comment by andreiw** [comment]
You can try serial port as well. What I do is spam the esc key as soon as ai apply power (do not wait for video to come up)

Alternatively, just place a fresh rpi_rfi.fd and try configuration again.
