### ISSUE TITLE
How to add more than one Ethernet port

### ISSUE THREAD

**Issue by Fnckerpoi** [andreiw/RaspberryPiPkg#119]
I want to add another Ethernet port through USB to connect to the Ethernet port to realize the Dual Ethernet port, but after inserting the adapter, the device can not recognize the new Ethernet port.

**Comment by andreiw** [comment]
You want to have several ethernet ports in UEFI? In Windows? In Linux?

This is a bug tracker for the low level
Firmware/BIOS for the Pi.
