### ISSUE TITLE
How to get this working?

### ISSUE THREAD

**Issue by ThatsFluke** [andreiw/RaspberryPiPkg#122]
Hey how do you install this bios onto a SD card and get it to boot to an image on the SD card? Thanks, I used Windows on Arm with this, but want to have this bios so I can boot from usb's or SD cards without editing the config. And overclocking without the config. I might even be able to run x86 Linux etc.

**Comment by mariobalanica** [comment]
Create a FAT32 partition on the SD card and copy the boot files to it.
If you want to overclock the CPU without editing the config.txt file, use this UEFI binary: [RPI_EFI.zip](https://github.com/andreiw/RaspberryPiPkg/files/2967419/RPI_EFI.zip)

You can't run x86 operating systems on the Pi.
