### ISSUE TITLE
CPU clock issue

### ISSUE THREAD

**Issue by BaRRaKudaRain** [andreiw/RaspberryPiPkg#124]
I've set  in UEFI CPU clock to Max setting (1400 MHz). And when I'm starting Windows 10 on my RPi 3B+ in Task Manager after each reboot it shows me different CPU clock values (600 MHz, 860 Mhz 999 MHz 1,20 GHz) Where is the problem? How to fix it?

**Comment by Andrew752** [comment]
I think the problem is in your power supply (Charger or the USB cable). Try to change them.

**Comment by Andrew752** [comment]
Look around in this Issue [https://github.com/andreiw/RaspberryPiPkg/issues/83] it was my problem too someday :)

**Comment by BaRRaKudaRain** [comment]
@Andrew752 Thank you! You're best! Pi works perfectly after changing power supply.
