### ISSUE TITLE
WIN10 (ARM) reboot after BIOS setup

### ISSUE THREAD

**Issue by joke1014** [andreiw/RaspberryPiPkg#125]
WIN10 (ARM) version has been saved to SD card

The raspberry pie is energized after inserting keyboard, mouse and screen

Press ESC to enter BIOS and set it as pictures

The problem in the last photo occurs when the keyboard is removed and the mouse is restarted.

How can I solve this problem?
![31101](https://user-images.githubusercontent.com/49181574/55378718-c0152f00-554c-11e9-9435-51e80dff3ef2.jpg)
![31102](https://user-images.githubusercontent.com/49181574/55378751-df13c100-554c-11e9-88f6-5b0f12e30029.jpg)
![31103](https://user-images.githubusercontent.com/49181574/55378754-e1761b00-554c-11e9-933b-3089f6a9a1f5.jpg)
![31104](https://user-images.githubusercontent.com/49181574/55378758-e33fde80-554c-11e9-97ff-4e5fe7a91223.jpg)
![31105](https://user-images.githubusercontent.com/49181574/55378760-e5a23880-554c-11e9-98dd-b8c90dd5f27d.jpg)
![31106](https://user-images.githubusercontent.com/49181574/55378761-e76bfc00-554c-11e9-8c22-9274c11d3438.jpg)
![31111](https://user-images.githubusercontent.com/49181574/55378762-e935bf80-554c-11e9-9b5b-5252091649a8.jpg)

**Comment by BenNottelling** [comment]
You need to change your boot order

**Comment by joke1014** [comment]
> 您需要更改引導順序

Can you tell me exactly how to do it?

**Comment by joke1014** [comment]
> You need to change your boot order

Can you tell me exactly how to do it?

**Comment by joke1014** [comment]
> You need to change your boot order

Can you tell me exactly how to do it?
Because both BOOT EL1 and EL2 have tried it.

**Comment by laurinneff** [comment]
I don't have this on my SD yet, but I'm guessing it's Boot Manager in the main menu

**Comment by andreiw** [comment]
Boot manager -> boot order -> make the usb key with woa first

On upstreamed edk2-platforms this issue no longer exists

**Comment by mullcom** [comment]
How do I get this bios on raspberry?
