### ISSUE TITLE
WD Pi Drive shuts down during boot. (USB Boot problems)

### ISSUE THREAD

**Issue by MikeDev101** [andreiw/RaspberryPiPkg#138]
Let's just start of by saying I'm a noob with this project, and GitHub in general. I know that there were a few posts similar to usb booting problems, and also how molasses slow the SD interface is. I tried copying the now ready "Windows On Raspberry Pi" Micro SD card to my 250GB Western Digital Pi Drive. It loaded the UEFI boot manager fine, but after it begins loading Windows it shuts down the USB interface and also shuts off the HDD, resulting in a BSoD "INACCESSIBLE_BOOT_DEVICE". Any suggestions?

I would also like to say that I'm using a Raspberry Pi 3 Model B, with a broken WiFi/Bluetooth chip. I'd be lucky if it doesn't start burning up. I could just run this on my other Pi, but it's just dead at this point...

I mainly chose to install Windows on a Pi because recently my Gl. iNet mt300n v2 mini wifi router got corrupted, and I need some small, quiet, low powered device to run as an network bridge, from a EasyTether USB interface to a hardwired Ethernet connection, all the way to a WiFi router/my network infrastructure. I would use Raspbian, but I'm also a noob with Linux, and when I did try it didn't work. With that in mind, I found out about this project and Windows was the way to go. But now this roadblock on any attempt to improve the speed now exists, so...?

Edit: Whoops, I may have posted this in the wrong repository. But I may just leave this here to see how it goes...

**Comment by mariobalanica** [comment]
You need a powered USB hub.
Keep in mind that Windows is way slower than Linux on the Raspberry Pi.

**Comment by MikeDev101** [comment]
But I was already doing that? It shuts down the USB interface, but my drive still has power. It assumes it got unmounted, and goes into some sort of "sleep mode".

**Comment by mariobalanica** [comment]
What tool have you used to install Windows on the SD card?

**Comment by andreiw** [comment]
This repo is deprecated and I don't check these conversations.
