### ISSUE TITLE
Black screen on boot (was: RPi3B+ support)

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#14]
I don't have this board (yet) and others have reported it as not working.

What I'd like are serial logs from a DEBUG build.

Note: you'll have to use newer bootcode.bin, start.elf and fixup.dat... i.e. ones known to support Pi 3 B+. You should be able to get these from a Rasbian distribution that supports the B+.

**Comment by falkor2k15** [comment]
Not sure how to get those logs, otherwise I could help. I will post on the relevant forum, and see if I can get anyone else to help.

**Comment by falkor2k15** [comment]
Nobody seems to know what "serial log" means, but are happy to help if given exact instructions.

**Comment by esnowberg** [comment]
Debug log attached from a RPi 3 B+

[RPi3B+-log.txt](https://github.com/andreiw/RaspberryPiPkg/files/1959129/RPi3B.-log.txt)

**Comment by andreiw** [comment]
@falkor2k15 by serial log I meant output from the serial port (mini-UART pins) to help triage what exactly doesn't work.

**Comment by andreiw** [comment]
@esnowberg Thanks a lot. The log seems to boot all the way to the Shell. Are you able to interact with UEFI through the serial console (be sure to keep hardware and software flow control off in minicom or similar software). Is it that the HDMI doesn't work?

**Comment by esnowberg** [comment]
@andreiw Yes, I can interact with UEFI through both the serial console and the USB keyboard.  HDMI works too.

I just substituted bootcode.bin, start.elf and the fixup code from 4-18 Raspbian Stretch Lite.

**Comment by andreiw** [comment]
So that means the new board will be supported as soon as I replace the VC firmware bits. Very cool. Thanks.

A

**Comment by andreiw** [comment]
Gonna leave this open until I can get a board and validate.

**Comment by andreiw** [comment]
Limited testing - I didn't boot Linux so I don't know if there are inherent device tree differences. You should follow the instructions for a custom device tree and use the relevant Pi3B+ device trees if such are needed for your OS.

I updated the VC firmware bits in the May 9th builds, too. It would be nice to be able to distinguish Pi3B+ and Pi3 in UEFI, I'll put that on my list, but in the mean time this is getting resolved as complete.

**Comment by andreiw** [comment]
In case it wasn't obvious Pi3B+ seems supported. I've one now :-)

**Comment by JulyIGHOR** [comment]
Not works for me. Black screen after rainbow screen. RPi3B+

**Comment by JulyIGHOR** [comment]
It hard to understand what folder tree have to be on microSD.
Can you please send complete folder tree of FAT32 partition? I think it also should be in readme file.

**Comment by andreiw** [comment]
Try the May13th, in case you has stale bits for some reason... 

MD5 (RPI_EFI.fd) = 0923fda247b8e3aea9db7d2ce9995611
MD5 (bootcode.bin) = 17efaf1c1ef89289168d71cdc8194982
MD5 (config.txt) = 5ecb180ae22cd884d5ae5a7384d939bf
MD5 (fixup.dat) = ab0a486fd2da88c03eb3f72f1e38fc7c
MD5 (readme.md) = ba05961520ec3f8c5bc22def5efc23b3
MD5 (start.elf) = 7713734f5909d0109ff57c0ed825eb0f

Proof:

![image](https://user-images.githubusercontent.com/732523/39971359-8ca41a70-56c7-11e8-88c4-63afee2a7680.png)

**Comment by andreiw** [comment]
Well, it's hard to say what is or what isn't a problem... do you have a non B+ Pi3 to try? Do you have a UART adapter to see what could be happening?

**Comment by JulyIGHOR** [comment]
No, I don't have another devices. I don't have UART adapter.
Should I try DEBUG folder?

**Comment by JulyIGHOR** [comment]
Pressing Ctrl+Alt+DEL makes device reboot, so it looks like everything works fine behind black screen.

**Comment by andreiw** [comment]
Was going to suggest that... now, a debug build may have different timing and thus may work... most likely your TV is not awake by the time the display driver initializes. I'll file a bug and see if I can get deferred initialization working. Until then, I recommend a different screen , sorry :-/

**Comment by andreiw** [comment]
Closing this issue - the video issue seen will be tracked separately.

**Comment by andreiw** [comment]
Can you try this image?

[RPI_EFI.fd.zip](https://github.com/andreiw/RaspberryPiPkg/files/1999332/RPI_EFI.fd.zip)

If that does help your black screen issue, also apply these config.txt changes. Without my comments, of course.

hdmi_force_hotplug=1 <-- allows plugging in video after system is booted
hdmi_group=1 <--- CEA modes (use 2 for DTM)
hdmi_mode=4 <-- pick a mode (this is 720p 60Hz)

**Comment by JulyIGHOR** [comment]
Latest build works, with no changes to config.txt
Thanks!

**Comment by andreiw** [comment]
w00t
