### ISSUE TITLE
How to set the default boot drive?

### ISSUE THREAD

**Issue by kenthinson** [andreiw/RaspberryPiPkg#141]
Hello. I was reading through the docs but can't find an answer. How do you set the default boot drive? Right now I have this boot loader on the SD card and the OS installed on a USB drive. The boot loader goes directly to the efi shell. I have to select the USB drive every time I boot.

**Comment by mariobalanica** [comment]
- Go to _Boot Maintenance Manager_ -> _Boot Options_ -> _Change Boot Order_ and press enter
- Highlight the SD card controller or the USB device (if you’re booting from USB) and use the 
`Shift and +` key combo to move the selection to the top, then press enter again

**Comment by kenthinson** [comment]
Thanks!
