### ISSUE TITLE
Can you make this for RaspberryPi 4b?I need it!

### ISSUE THREAD

**Issue by xiaokang00010** [andreiw/RaspberryPiPkg#142]

**Comment by ShireCiel** [comment]
> _No description provided._

UEFI of RPI4B is available on https://github.com/andreiw/lampone.
UEFI is ok. But there is no any windows driver support yet. 
Some detail how to boot. Please see issues in that project.

**Comment by andreiw** [comment]
Go to https://rpi4-uefi.dev for latest status.
