### ISSUE TITLE
Outdated UEFI with WoR Project

### ISSUE THREAD

**Issue by Antonios-P** [andreiw/RaspberryPiPkg#144]
Grettings - I have been having a small issue with the UEFI files. I have downloaded the latest prebuilt firmware which is the Jan16-2019 version. According to ```latest```, it should be the Feb18-2019 version. That file is non-existent. I am having issues because the software thinks that there is a later version available when there isn't. It then fails to download. Adding the new prebuilt file or changing ```latest``` would be fantastic. Thanks.

**Comment by andreiw** [comment]
Sorry, I don't run WoR project. Also, you shouldn't be looking at this historical outdated repo - go to https://github.com/tianocore/edk2-platforms/tree/master/Platform/RaspberryPi/RPi3. You'll be right to notice there are no prebuilts. I don't make any anymore as effort has shifted to https://rpi4-uefi.dev.
