### ISSUE TITLE
Error during building

### ISSUE THREAD

**Issue by xCuri0** [andreiw/RaspberryPiPkg#15]
During building I get this error ```ArmPlatformPkg/Library/ArmPlatformSysConfigLibNull/ArmPlatformSysConfigLibNull.inf is not found in packages path:```

**Comment by andreiw** [comment]
Can you paste the whole error output and your exact build steps? What is your compiler?

**Comment by xCuri0** [comment]
@andreiw I followed the build instructions and that is the only error. Compiler is GCC 5.4 on Ubuntu 16.04 amd64

**Comment by xCuri0** [comment]
@andreiw i was using the latest version of edk2 so maybe thats why
