### ISSUE TITLE
Some displays don't work

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#17]
A few displays/TVs handshake so slowly that the display driver doesn't detect anything when it is loaded. Need to make video initialization asynchronous.

**Comment by andreiw** [comment]
Making it asynchronous doesn't really help because it's the VC that does HDMI handshaking, and unless we have a full-blown VCHIQ driver, this isn't going to go anywhere...

A reasonable workaround is (in config.txt)
hdmi_force_hotplug=1 <-- allows plugging in video *after* system is booted
hdmi_group=1  <--- CEA modes (use 2 for DTM)
hdmi_mode=4 <-- pick a mode (this is 720p 60Hz)

**Comment by JulyIGHOR** [comment]
It does works now. Thank you!
