### ISSUE TITLE
Packaging Request - Tarballs of Known Good Binaries

### ISSUE THREAD

**Issue by gordan-bobic** [andreiw/RaspberryPiPkg#2]
Any chance you could (periodically) post a "release" tarball containing a known good combination of the firmware blobs and RPI_EFI.fd? That would save a LOT of time.

**Comment by andreiw** [comment]
Done.

See Binary/prebuilt/2018Jan13-GCC49. You can just copy the contents of RELEASE or DEBUG to empty boot media.
