### ISSUE TITLE
Official Raspberry Pi 7" Touchscreen as Display

### ISSUE THREAD

**Issue by pixelomer** [andreiw/RaspberryPiPkg#20]
Hi, I want to use my touchscreen as a monitor for both UEFI boot menu and the operating systems. Is it possible? I don't need touch support, I just need the display.

**Comment by andreiw** [comment]
Did you try?

A

**Comment by pixelomer** [comment]
Yes I did, I only got a blank screen.

**Comment by andreiw** [comment]
If you have a UART cable, run the DEBUG variant if firmware and send me the full output. It is possible the resolution is too low.  What is the resolution supported?

**Comment by pixelomer** [comment]
No, I don't have any UART cables. The touchscreen's resolution is 800x480. Is it too low?

**Comment by andreiw** [comment]
I’ll see what I can do.

A

**Comment by driver1998** [comment]
BTW, composite displays hangs at the rainbow screen.

**Comment by andreiw** [comment]
What’s a “composite display”?

A

**Comment by driver1998** [comment]
That is the composite video output built in to the 3.5mm jack.

**Comment by andreiw** [comment]
Woah, I totally didn't know the new Pies could still do that! Very cool.

Still to look at the resolution issue, hold on!

**Comment by andreiw** [comment]
This should be resolved as of the https://github.com/andreiw/RaspberryPiPkg/tree/master/Binary/prebuilt/2018May27-GCC49 build.

Let me know.

**Comment by driver1998** [comment]
Both NTSC and PAL mode works, I don't have an official 7" touch screen handy so cannot test that.
BTW, you can get rid of the resolution problem (being smaller than the one got from the GPU) by specify "disable_overscan=1" in config.txt, this works for me.

**Comment by pixelomer** [comment]
Windows 10 on ARM is displayed completely fine on the 7" screen. Obviously the touch screen doesn't work, it just works as a display,. We need a driver for windows to use the touch screen, right?

**Comment by andreiw** [comment]
yep

A
