### ISSUE TITLE
Blue screen of death stop code DRIVER POWER STATE FAILURE

### ISSUE THREAD

**Issue by manamster** [andreiw/RaspberryPiPkg#24]
Every time I have rebooted or turned on the rpi I get stuck in an endless loop of blue screens. I haven't even finished installing because I can't get past the blue screens.

**Comment by thchi12** [comment]
Don't plug any usb devices while booting.

**Comment by manamster** [comment]
I'll try that and get back to you.

**Comment by andreiw** [comment]
Also, join the discussion in https://github.com/andreiw/RaspberryPiPkg/issues/12 instead.

This is not an UEFI firmware issue.
