### ISSUE TITLE
Use ACPI also for booting Linux

### ISSUE THREAD

**Issue by Googulator** [andreiw/RaspberryPiPkg#27]
Currently it appears that only Windows is booted using ACPI, while Linux gets traditional DTBs, which are distro-specific.

Linux supports ACPI for device discovery on ARM64 since version 4.1. It would be handy to reuse the ACPI support developed for Windows also in Linux, possibly avoiding having to go distro-specific.

**Comment by andreiw** [comment]
To a degree, this may be possible, but will be pointless if the end result will depend on someone adding ACPI support to critical RPi drivers in Linux.

A

**Comment by woachk** [comment]
@andreiw why not adding ACPI support to those drivers then? it's doing it once..

**Comment by andreiw** [comment]
Sure, why not? Due to PRP0001 the only real
place to pay attention may just be the MADT parsing (i.e. don’t try parsing for a GIC on a Pi)...

A
