### ISSUE TITLE
Very Slow Clock Ticks

### ISSUE THREAD

**Issue by gordan-bobic** [andreiw/RaspberryPiPkg#3]
It looks like the timer countdown in grub is very slow after being booted by this build of Tianocore. It takes 2-3 seconds to tick down by 1 second on the boot menu screen.

**Comment by andreiw** [comment]
I can't confirm this with either the tickdown in the UEFI Shell, or the openSUSE grub. I tested the two RPi3s I have, both with and without serial.

Try one of my prebuilts and let me know.

**Comment by andreiw** [comment]
Okay, closing as no repro

**Comment by andreiw** [comment]
This was likely caused by USB error spew in early split transfer code, due to an unsupported keyboard attached. Serial logs would have helped. Issue should be resolved now.
