### ISSUE TITLE
[Proposal] Redistribute Installed iso/virtualdisk of latest release

### ISSUE THREAD

**Issue by dangi12012** [andreiw/RaspberryPiPkg#30]
Instead of installing Windows for every new build (which takes 5 hours) can you also supply a Image of a finished installation?

That way we can just clone that iso or vhd to the SD Card and direcly use it.

Alternatively if there is a technicality why this is impossible, the installing process can be automated. 
If a automatic installer is needed I can supply one, but I need to hear from Authors first if option A is possible.

**Comment by andreiw** [comment]
RaspberryPiPkg is an UEFI firmware package for the Pi. The motivation is to have a reference UEFI implementation for further development. Yes, it boots Linux. Yes, it boots FreeBSD and yes - part of the value provided is the ability to boot Windows NT, but the project does not focus on getting NT to run well, drivers, installation and so on.

Also, keep in mind that it may be illegal to distribute Windows images (ISOs or VHDs). I'm not Microsoft, don't make the call, and don't need that drama in my life, but you're welcome (along with the rest of the community in https://github.com/andreiw/RaspberryPiPkg/issues/12) to try rolling together a Windows distribution for the Pi.
