### ISSUE TITLE
[Proposal] Boot from USB Drive

### ISSUE THREAD

**Issue by dangi12012** [andreiw/RaspberryPiPkg#31]
I hear that there are many problems with the SD Card speed. Raspberry supports alternative boot mode from a USB Device:
[https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md](url)

Have you ever tried creating Images for an external USB device? Also I dont know what driver is used for that but I suppose it could be faster than the one from the SD card.

**Comment by andreiw** [comment]
UEFI can boot from USB stick itself, and I highly recommend installing any OSes (like Linux, etc) onto USB as well.

If/when/once Windows 10 for Pi gets a better dwusb driver, please use USB as well, but this is not a UEFI problem.
