### ISSUE TITLE
SMBIOS Type 0 Version String

### ISSUE THREAD

**Issue by imbushuo** [andreiw/RaspberryPiPkg#32]
https://github.com/andreiw/RaspberryPiPkg/blob/137a9ec4b777b8452103ac5f900d858136187e40/Drivers/PlatformSmbiosDxe/PlatformSmbiosDxe.c#L132

[Per SMBIOS specification](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.2.0.pdf), this string should be `mm/dd/yyyy`:
> String number of the BIOS release date. The date string, if supplied, is in either mm/dd/yy or mm/dd/yyyy format. If the year portion of the string is two digits, the year is assumed to be 19yy.
> NOTE: The mm/dd/yyyy format is required for SMBIOS version 2.3 and later.

Otherwise Windows prints some weird things, like BIOS Release 1/1/1601 (the minimum value in Windows time structure).

**Comment by andreiw** [comment]
![image](https://user-images.githubusercontent.com/732523/41269953-73e2aa30-6dd6-11e8-9e2e-26789a96a360.png)

![image](https://user-images.githubusercontent.com/732523/41270309-7aa41744-6dd8-11e8-8e40-7c68f6759e23.png)

Will be fixed. Thanks for your report.
