### ISSUE TITLE
Errors when building HypDxe

### ISSUE THREAD

**Issue by thchi12** [andreiw/RaspberryPiPkg#34]
/mnt/f/src/RaspberryPiPkg/Drivers/HypDxe/HypLog.c: In function ‘HypLogSetColors’:
/mnt/f/src/RaspberryPiPkg/Drivers/HypDxe/HypLog.c:53:1: error: type of ‘Color’ defaults to ‘int’ [-Werror=implicit-int]
GNUmakefile:439: recipe for target '/mnt/f/src/Build/RaspberryPiPkg-AARCH64/RELEASE_GCC5/AARCH64/RaspberryPiPkg/Drivers/HypDxe/HypDxe/OUTPUT/HypLog.obj' failed
 HypLogSetColors(
Building ... /mnt/f/src/RaspberryPiPkg/Drivers/RpiFdtDxe/RpiFdtDxe.inf [AARCH64]
 ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [/mnt/f/src/Build/RaspberryPiPkg-AARCH64/RELEASE_GCC5/AARCH64/RaspberryPiPkg/Drivers/HypDxe/HypDxe/OUTPUT/HypLog.obj] Error 1

build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/f/src/Build/RaspberryPiPkg-AARCH64/RELEASE_GCC5/AARCH64/RaspberryPiPkg/Drivers/HypDxe/HypDxe]

build.py...
 : error F002: Failed to build module
        /mnt/f/src/RaspberryPiPkg/Drivers/HypDxe/HypDxe.inf [AARCH64, GCC5, RELEASE]
Host is Ubuntu 18.04 under WSL with gcc-7. Maybe an earlier version of gcc is needed?

**Comment by Googulator** [comment]
> STATIC VOID
> HypLogSetColors(
>   IN  Color
> )

That's indeed missing a type specification for Color.
