### ISSUE TITLE
Merge SdHostDxe support

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#35]
Merge https://github.com/andreiw/RaspberryPiPkg/pull/33 in a way to allow either host controller to be used (setup controlled).

**Comment by Googulator** [comment]
I'm afraid this may not work in a configurable way, unless we can disable the Arasan driver completely at runtime (while leaving GPIO 34-39 routed to it), as the Arasan driver locks up when it sees the SDIO WiFi chip.

**Comment by andreiw** [comment]
This is coming along pretty well - including 4bit 50MHz mode. I need to figure out some stability issues with a few cards that I have...

**Comment by andreiw** [comment]
Done
