### ISSUE TITLE
Write tool to support booting hybrid GPT/MBR disks in UEFI (for Windows)

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#36]
Merge https://github.com/Googulator/RaspberryPiPkg/commit/844a02a473b147e621e8d4709b6eaababd8fa2d9 in a TBD fashion

**Comment by Googulator** [comment]
Looks like this won't be needed after all, see my comment in the megathread.

**Comment by Googulator** [comment]
So, all that the tool needs to do is this (assuming ESP at sector 2048):
1. Copy 76 bytes from offset 0x10000B to offset 0xB
2. Increment byte at offset 0xF by 8

On Linux, this is trivial. On Windows, it's a PITA due to how Windows handles physical device writes.

**Comment by mariobalanica** [comment]
Setting the FAT32 boot MBR partition as active also fixes the first boot error.
The only issue is that after Windows finishes the configuration it will hang at a black screen and restart if any USB device is plugged in. After that it will boot normally.

**Comment by andreiw** [comment]
So there is no need for a hybrid GPT?

A

**Comment by mariobalanica** [comment]
No.
