### ISSUE TITLE
DwUsbHostDxe: HP FD-05PUB usb floppy doesn't work

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#4]
This is a CBI mass storage device (UFI).

Plugging it in nukes the RPi hub somehow. Connected devices still work, but
UsbBusDxe cannot enumerate ports anymore.

**Comment by andreiw** [comment]
Tried another CBI device and same deal. Both the device and the hub port the device is plugged into fail.

**Comment by hansmbakker** [comment]
Is this issue still an issue with the new usb driver?

**Comment by andreiw** [comment]
Well, it’s open. That means it is still an issue.

A

**Comment by andreiw** [comment]
Still and issue but this needs to be developed upstream, not here - https://github.com/tianocore/edk2-platforms/tree/master/Platform/RaspberryPi/RPi3
