### ISSUE TITLE
[help] Can support Aarch64 debian on Pi 3B with tf card ?

### ISSUE THREAD

**Issue by aiminickwong** [andreiw/RaspberryPiPkg#40]
I have test with, Aarch64 debian can start normal, but can not start with this.

**Comment by aiminickwong** [comment]
@Googulator I don't know much about  SBSA, I used debian official repo with debootstrap tools and build the rootfs, built the kernel add uefi supoort .  All of this with CROSS_COMPILE.
Do not use RaspberryPiPkg Boot loader, everything is ok with normal boot and RPi office loader ,but cant not boot with RaspberryPiPkg.

**Comment by thchi12** [comment]
Maybe your debian doen't have an efi bootloader?

**Comment by aiminickwong** [comment]
@thchi12 what you mean about efi bootloader?  it's uefi support for kernel?  I'm quite sure I have make UEFI support  in Kernel build. So I don't known the efi bootloader what's it could you tell me, please :)  Thank you.

**Comment by aiminickwong** [comment]
@thchi12 I have make EFI Boot Stub In kernel and let pi support start direct from kernel in EFI mode , cuz grub-uefi I don't know how to used to boot the kernel with the Tiano Core so I have just test EFI Boot Stub, but it's not work On Pi 3b+ （：

**Comment by andreiw** [comment]
alright stay tuned...

when you boot the regular way, do you override the dtb? What is the config.txt when you boot Debian directly?

A

**Comment by andreiw** [comment]
Okay so you had to build your own kernel.

Can you qualify what "does not work" mean? What do you see on the serial console? "Exiting boot stub" message from the kernel and that's it?

I noticed that on the Pi Debian image there's a DTB distributed.  Can you follow the directions in https://github.com/andreiw/RaspberryPiPkg#custom-device-tree to make sure that DTB is used to boot your Debian kernel?

**Comment by andreiw** [comment]
Also follow https://github.com/andreiw/RaspberryPiPkg#custom-bootargs to make sure the correct command line is passed.

**Comment by andreiw** [comment]
I can help you debug this further, but I don't have the time to install Debian and then build a custom kernel for the Pi with EFI stub support. You're welcome to attach your built kernel here as an attachment, though, if you would like me to take a look.

**Comment by aiminickwong** [comment]
@andreiw I'll be back when I test again and collect some necessary information. Thank you.

**Comment by aiminickwong** [comment]
I forget report,  before testing, I can not normally boot when power on I get the Rainbow screen, nothing go on with out any logs,  I rename the kernel8.img to k8 and boot to EFI shell and input "k8" to testing BOOT.
Now I have testing again, and with  UART tty console.

#### 1st is boot screen error, this info can not display on UART tty console screen.
----
![wechatimg22](https://user-images.githubusercontent.com/6368382/41790813-5815baa0-7686-11e8-9d95-5d7caa3d0e24.jpeg)

#### UART tty console error when boot k8:
----
Shell> k8
FSOpen: Open '\k8' Success
FSOpen: Open '\k8' Success
FSOpen: Open '\k8' Success
FSOpen: Open '\k8' Success
[Security] 3rd party image[0] can be loaded after EndOfDxe: VenHw(58ABD787-F64D-4CA2-A034-B9AC2D5AD0CF)/HD(1,MBR,0x65FAAEF4,0x2000,0x1F800)/\k8.
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 35FF3240
Loading driver at 0x00032901000 EntryPoint=0x000333C695C
Loading driver at 0x00032901000 EntryPoint=0x000333C695C
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 35FF3E18
ProtectUefiImageCommon - 0x35FF3240
  - 0x0000000032901000 - 0x0000000000F4F000
InstallProtocolInterface: 752F3136-4E16-4FDC-A22A-E5F46812F4CA 3B3FF5B8
EFI stub: Booting Linux Kernel...
EFI stub: EFI_RNG_PROTOCOL unavailable, no randomness supplied
ConvertPages: range 80000 - FCFFFF covers multiple entries
EFI stub: Using DTB from configuration table
EFI stub: Exiting boot services and installing virtual address map...
Exiting UEFI Boot Services!
----> Exiting UEFI and booting OS kernel! <----
SetUefiImageMemoryAttributes - 0x0000000037260000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x0000000033EF0000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x0000000033EA0000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x0000000033E30000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x0000000033D90000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x0000000033C10000 - 0x0000000000040000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x0000000033B70000 - 0x0000000000040000 (0x0000000000000008)

#### tty start boot log:
----
[UART tty console error.txt](https://github.com/andreiw/RaspberryPiPkg/files/2128622/UART.tty.console.error.txt)

#### config:
----
arm_control=0x200
enable_uart=1
armstub=RPI_EFI.fd
disable_commandline_tags=1
device_tree_address=0x8000
device_tree_end=0x10000
device_tree=bcm2710-rpi-3-b-plus.dtb
----
#### cmdline:
--------
dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes net.ifnames=0 rootwait
----

#### my whole boot partition zip pkg include kernel file.
----
[boot.zip](https://github.com/andreiw/RaspberryPiPkg/files/2128641/boot.zip)

**Comment by aiminickwong** [comment]
#### normal boot log with out EFI:
----
pi@raspbian:~$ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.50-OPENFANS+CecOS-v8 (root@debian) (gcc version 6.3.0 20170516 (Debian 6.3.0-18)) #1 SMP PREEMPT Fri Jun 22 21:26:25 CST 2018
[    0.000000] Boot CPU: AArch64 Processor [410fd034]
[    0.000000] Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] efi: Getting EFI parameters from FDT:
[    0.000000] efi: UEFI not found.
[    0.000000] cma: Reserved 8 MiB at 0x000000003ac00000
[    0.000000] On node 0 totalpages: 242688
[    0.000000]   DMA zone: 3792 pages used for memmap
[    0.000000]   DMA zone: 0 pages reserved
[    0.000000]   DMA zone: 242688 pages, LIFO batch:31
[    0.000000] percpu: Embedded 22 pages/cpu @fffffff6fab7a000 s50968 r8192 d30952 u90112
[    0.000000] pcpu-alloc: s50968 r8192 d30952 u90112 alloc=22*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: enabling workaround for ARM erratum 845719
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 238896
[    0.000000] Kernel command line: 8250.nr_uarts=1 bcm2708_fb.fbwidth=1824 bcm2708_fb.fbheight=984 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=PARTUUID=546dba46-02 rootfstype=ext4 elevator=deadline fsck.repair=yes net.ifnames=0 rootwait
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.000000] Memory: 928368K/970752K available (8316K kernel code, 978K rwdata, 2672K rodata, 2944K init, 720K bss, 34192K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     modules : 0xffffff8000000000 - 0xffffff8008000000   (   128 MB)
[    0.000000]     vmalloc : 0xffffff8008000000 - 0xffffffbebfff0000   (   250 GB)
[    0.000000]       .text : 0xffffff8541280000 - 0xffffff8541aa0000   (  8320 KB)
[    0.000000]     .rodata : 0xffffff8541aa0000 - 0xffffff8541d40000   (  2688 KB)
[    0.000000]       .init : 0xffffff8541d40000 - 0xffffff8542020000   (  2944 KB)
[    0.000000]       .data : 0xffffff8542020000 - 0xffffff8542114a00   (   979 KB)
[    0.000000]        .bss : 0xffffff8542114a00 - 0xffffff85421c8ce8   (   721 KB)
[    0.000000]     fixed   : 0xffffffbefe7fb000 - 0xffffffbefec00000   (  4116 KB)
[    0.000000]     PCI I/O : 0xffffffbefee00000 - 0xffffffbeffe00000   (    16 MB)
[    0.000000]     vmemmap : 0xffffffbf00000000 - 0xffffffc000000000   (     4 GB maximum)
[    0.000000]               0xffffffbfdb000000 - 0xffffffbfdbed0000   (    14 MB actual)
[    0.000000]     memory  : 0xfffffff6c0000000 - 0xfffffff6fb400000   (   948 MB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 28148 entries in 110 pages
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000]  Tasks RCU enabled.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000231] Console: colour dummy device 80x25
[    0.001073] console [tty1] enabled
[    0.001114] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=19200)
[    0.001160] pid_max: default: 32768 minimum: 301
[    0.001506] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.001553] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.002560] Disabling memory control group subsystem
[    0.007107] ASID allocator initialised with 32768 entries
[    0.009105] Hierarchical SRCU implementation.
[    0.011355] EFI services will not be available.
[    0.013172] smp: Bringing up secondary CPUs ...
[    0.020373] Detected VIPT I-cache on CPU1
[    0.020441] CPU1: Booted secondary processor [410fd034]
[    0.027479] Detected VIPT I-cache on CPU2
[    0.027526] CPU2: Booted secondary processor [410fd034]
[    0.034595] Detected VIPT I-cache on CPU3
[    0.034637] CPU3: Booted secondary processor [410fd034]
[    0.034775] smp: Brought up 1 node, 4 CPUs
[    0.034903] SMP: Total of 4 processors activated.
[    0.034933] CPU features: detected feature: 32-bit EL0 Support
[    0.034962] CPU features: detected feature: Kernel page table isolation (KPTI)
[    0.038345] CPU: All CPU(s) started at EL2
[    0.038395] alternatives: patching kernel code
[    0.039685] devtmpfs: initialized
[    0.051850] random: get_random_u32 called from bucket_table_alloc+0xf8/0x288 with crng_init=0
[    0.052543] Enabled cp15_barrier support
[    0.052584] Enabled setend support
[    0.052921] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
[    0.052976] futex hash table entries: 1024 (order: 5, 131072 bytes)
[    0.053616] xor: measuring software checksum speed
[    0.062819]    8regs     :  1144.000 MB/sec
[    0.072918]    8regs_prefetch:  1020.000 MB/sec
[    0.083014]    32regs    :  1352.000 MB/sec
[    0.093112]    32regs_prefetch:  1148.000 MB/sec
[    0.093139] xor: using function: 32regs (1352.000 MB/sec)
[    0.093173] pinctrl core: initialized pinctrl subsystem
[    0.093441] DMI not present or invalid.
[    0.093786] NET: Registered protocol family 16
[    0.098758] cpuidle: using governor menu
[    0.099196] vdso: 2 pages (1 code @ ffffff8541aa7000, 1 data @ ffffff8542024000)
[    0.099246] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.102580] DMA: preallocated 256 KiB pool for atomic allocations
[    0.102733] Serial: AMBA PL011 UART driver
[    0.104998] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.105651] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.155956] raid6: int64x1  gen()   222 MB/s
[    0.173191] raid6: int64x1  xor()   224 MB/s
[    0.190246] raid6: int64x2  gen()   347 MB/s
[    0.207422] raid6: int64x2  xor()   300 MB/s
[    0.224573] raid6: int64x4  gen()   503 MB/s
[    0.241701] raid6: int64x4  xor()   380 MB/s
[    0.258922] raid6: int64x8  gen()   558 MB/s
[    0.275985] raid6: int64x8  xor()   365 MB/s
[    0.293225] raid6: neonx1   gen()   375 MB/s
[    0.310321] raid6: neonx1   xor()   427 MB/s
[    0.327496] raid6: neonx2   gen()   597 MB/s
[    0.344592] raid6: neonx2   xor()   601 MB/s
[    0.361783] raid6: neonx4   gen()   773 MB/s
[    0.378904] raid6: neonx4   xor()   720 MB/s
[    0.396067] raid6: neonx8   gen()   816 MB/s
[    0.413199] raid6: neonx8   xor()   751 MB/s
[    0.413225] raid6: using algorithm neonx8 gen() 816 MB/s
[    0.413251] raid6: .... xor() 751 MB/s, rmw enabled
[    0.413277] raid6: using neon recovery algorithm
[    0.413720] bcm2835-dma 3f007000.dma: DMA legacy API manager at ffffff800801d000, dmachans=0x1
[    0.415477] SCSI subsystem initialized
[    0.415745] usbcore: registered new interface driver usbfs
[    0.415830] usbcore: registered new interface driver hub
[    0.415997] usbcore: registered new device driver usb
[    0.416225] dmi: Firmware registration failed.
[    0.416971] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-06-21 14:02
[    0.418622] clocksource: Switched to clocksource arch_sys_counter
[    0.530409] VFS: Disk quotas dquot_6.6.0
[    0.530534] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.530782] FS-Cache: Loaded
[    0.531045] CacheFiles: Loaded
[    0.541643] NET: Registered protocol family 2
[    0.542401] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    0.542544] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[    0.542818] TCP: Hash tables configured (established 8192 bind 8192)
[    0.543065] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.543136] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.543450] NET: Registered protocol family 1
[    0.544082] RPC: Registered named UNIX socket transport module.
[    0.544111] RPC: Registered udp transport module.
[    0.544134] RPC: Registered tcp transport module.
[    0.544156] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.546015] hw perfevents: enabled with armv8_pmuv3 PMU driver, 7 counters available
[    0.546215] kvm [1]: 8-bit VMID
[    0.547148] kvm [1]: Hyp mode initialized successfully
[    0.549263] workingset: timestamp_bits=46 max_order=18 bucket_order=0
[    0.559958] FS-Cache: Netfs 'nfs' registered for caching
[    0.560777] NFS: Registering the id_resolver key type
[    0.560833] Key type id_resolver registered
[    0.560858] Key type id_legacy registered
[    0.563476] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.563707] io scheduler noop registered
[    0.563736] io scheduler deadline registered (default)
[    0.564054] io scheduler cfq registered
[    0.564083] io scheduler mq-deadline registered
[    0.564110] io scheduler kyber registered
[    0.566868] BCM2708FB: allocated DMA memory fac40000
[    0.566928] BCM2708FB: allocated DMA channel 0 @ ffffff800801d000
[    0.605408] Console: switching to colour frame buffer device 228x61
[    0.624456] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    0.626236] bcm2835-rng 3f104000.rng: hwrng registered
[    0.626481] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.627456] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.627888] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.640724] brd: module loaded
[    0.652865] loop: module loaded
[    0.652984] Loading iSCSI transport class v2.0-870.
[    0.653652] iscsi: registered transport (tcp)
[    0.654233] libphy: Fixed MDIO Bus: probed
[    0.654459] usbcore: registered new interface driver lan78xx
[    0.654664] usbcore: registered new interface driver smsc95xx
[    0.654793] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.883057] Core Release: 2.80a
[    0.883142] Setting default values for core params
[    0.883266] Finished setting default values for core params
[    1.083686] Using Buffer DMA mode
[    1.083769] Periodic Transfer Interrupt Enhancement - disabled
[    1.083887] Multiprocessor Interrupt Enhancement - disabled
[    1.084004] OTG VER PARAM: 0, OTG VER FLAG: 0
[    1.084105] Dedicated Tx FIFOs mode
[    1.084790] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0x08181000 dma = 0xfac54000 len=9024
[    1.084999] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    1.085404] dwc_otg: Microframe scheduler enabled
[    1.085472] WARN::hcd_init_fiq:486: MPHI regs_base at 0x0803d000
[    1.085696] dwc_otg 3f980000.usb: DWC OTG Controller
[    1.085831] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    1.086008] dwc_otg 3f980000.usb: irq 15, io mem 0x00000000
[    1.090288] Init: Port Power? op_state=1
[    1.094563] Init: Power Port (0)
[    1.099045] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    1.103400] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.107664] usb usb1: Product: DWC OTG Controller
[    1.112062] usb usb1: Manufacturer: Linux 4.14.50-OPENFANS+CecOS-v8 dwc_otg_hcd
[    1.116482] usb usb1: SerialNumber: 3f980000.usb
[    1.121600] hub 1-0:1.0: USB hub found
[    1.125886] hub 1-0:1.0: 1 port detected
[    1.130860] dwc_otg: FIQ enabled
[    1.130869] dwc_otg: NAK holdoff enabled
[    1.130877] dwc_otg: FIQ split-transaction FSM enabled
[    1.130891] Module dwc_common_port init
[    1.131489] usbcore: registered new interface driver usb-storage
[    1.135994] IR NEC protocol handler initialized
[    1.140178] IR RC5(x/sz) protocol handler initialized
[    1.144494] IR RC6 protocol handler initialized
[    1.148791] IR JVC protocol handler initialized
[    1.153086] IR Sony protocol handler initialized
[    1.157204] IR SANYO protocol handler initialized
[    1.161394] IR Sharp protocol handler initialized
[    1.165566] IR MCE Keyboard/mouse protocol handler initialized
[    1.169761] IR XMP protocol handler initialized
[    1.174748] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    1.179359] bcm2835-cpufreq: min=600000 max=1400000
[    1.184141] sdhci: Secure Digital Host Controller Interface driver
[    1.188470] sdhci: Copyright(c) Pierre Ossman
[    1.193098] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    1.197895] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    1.202567] usbcore: registered new interface driver ushc
[    1.206865] Error: Driver 'sdhost-bcm2835' is already registered, aborting...
[    1.211252] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.218109] ledtrig-cpu: registered to indicate activity on CPUs
[    1.222580] hidraw: raw HID events driver (C) Jiri Kosina
[    1.227054] usbcore: registered new interface driver usbhid
[    1.231447] usbhid: USB HID core driver
[    1.236098] Initializing XFRM netlink socket
[    1.240468] NET: Registered protocol family 17
[    1.244963] Key type dns_resolver registered
[    1.250480] registered taskstats version 1
[    1.256773] Btrfs loaded, crc32c=crc32c-generic, assert=on
[    1.269804] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    1.274288] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 72, base_baud = 0) is a PL011 rev2
[    1.280900] console [ttyS0] disabled
[    1.285441] 3f215040.serial: ttyS0 at MMIO 0x0 (irq = 151, base_baud = 31250000) is a 16550
[    2.500091] console [ttyS0] enabled
[    2.509413] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    2.519939] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    2.530188] Indeed it is in host mode hprt0 = 00021501
[    2.600845] sdhost: log_buf @ ffffff80080b5000 (fac53000)
[    2.629320] random: fast init done
[    2.640409] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    2.652088] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    2.662650] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    2.674597] of_cfs_init
[    2.681652] of_cfs_init: OK
[    2.689455] Waiting for root device PARTUUID=546dba46-02...
[    2.699841] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    2.712715] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    2.722707] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.722915] Indeed it is in host mode hprt0 = 00001101
[    2.780077] mmc0: host does not support reading read-only switch, assuming write-enable
[    2.800007] mmc0: new high speed SDHC card at address 1234
[    2.816845] bounce: isa pool size: 16 pages
[    2.834870] mmcblk0: mmc0:1234 SA32G 28.9 GiB
[    2.846160]  mmcblk0: p1 p2
[    2.881589] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.894480] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    2.916167] mmc1: new high speed SDIO card at address 0001
[    2.926438] devtmpfs: mounted
[    2.939795] Freeing unused kernel memory: 2944K
[    2.961116] usb 1-1: New USB device found, idVendor=0424, idProduct=2514
[    2.972583] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.985255] hub 1-1:1.0: USB hub found
[    2.993754] hub 1-1:1.0: 4 ports detected
[    3.288688] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    3.388076] usb 1-1.1: New USB device found, idVendor=0424, idProduct=2514
[    3.399744] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.412286] systemd[1]: System time before build time, advancing clock.
[    3.424086] hub 1-1.1:1.0: USB hub found
[    3.433008] hub 1-1.1:1.0: 3 ports detected
[    3.566610] dwc_otg_handle_wakeup_detected_intr lxstate = 2
[    3.586319] NET: Registered protocol family 10
[    3.596828] Segment Routing with IPv6
[    3.620699] ip_tables: (C) 2000-2006 Netfilter Core Team
[    3.657912] random: systemd: uninitialized urandom read (16 bytes read)
[    3.679348] random: systemd: uninitialized urandom read (16 bytes read)
[    3.694736] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    3.718723] systemd[1]: Detected architecture arm64.
[    3.747865] systemd[1]: Set hostname to <raspbian>.
[    3.789884] random: systemd: uninitialized urandom read (16 bytes read)
[    3.912688] usb 1-1.3: new low-speed USB device number 4 using dwc_otg
[    4.029597] usb 1-1.3: New USB device found, idVendor=1c4f, idProduct=0002
[    4.041666] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    4.053979] usb 1-1.3: Product: USB Keyboard
[    4.063035] usb 1-1.3: Manufacturer: SIGMACHIP
[    4.083829] input: SIGMACHIP USB Keyboard as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:1C4F:0002.0001/input/input0
[    4.153333] hid-generic 0003:1C4F:0002.0001: input,hidraw0: USB HID v1.10 Keyboard [SIGMACHIP USB Keyboard] on usb-3f980000.usb-1.3/input0
[    4.182568] input: SIGMACHIP USB Keyboard as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.1/0003:1C4F:0002.0002/input/input1
[    4.219688] systemd[1]: [/etc/systemd/system/rc-local.service:11] Support for option SysVStartPriority= has been removed and it is ignored
[    4.252165] hid-generic 0003:1C4F:0002.0002: input,hidraw1: USB HID v1.10 Device [SIGMACHIP USB Keyboard] on usb-3f980000.usb-1.3/input1
[    4.257967] systemd[1]: Listening on Journal Socket.
[    4.287205] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    4.307228] systemd[1]: Listening on udev Kernel Socket.
[    4.325267] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    4.347355] systemd[1]: Listening on Journal Socket (/dev/log).
[    4.365854] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    4.390431] random: crng init done
[    4.399724] random: 7 urandom warning(s) missed due to ratelimiting
[    4.487701] usb 1-1.1.1: new high-speed USB device number 5 using dwc_otg
[    4.584597] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800
[    4.597531] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    4.904982] libphy: lan78xx-mdiobus: probed
[    5.068832] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    5.194915] systemd-journald[93]: Received request to flush runtime journal from PID 1
[    5.569419] vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    5.616131] vchiq: vchiq_init_state: slot_zero = ffffff800878b000, is_master = 0
[    5.993071] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43455-sdio.bin for chip 0x004345(17221) rev 0x000006
[    5.994209] usbcore: registered new interface driver brcmfmac
[    6.217400] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[    6.238722] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 9.10.105 Compiler: 1.29.4 ClmImport: 1.36.3 Creation: 2018-03-09 18:56:28
[    8.226377] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    8.233893] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    8.260419] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready

**Comment by andreiw** [comment]
did you build your own kernel? Please share it

A

**Comment by aiminickwong** [comment]
@andreiw I have upload https://github.com/andreiw/RaspberryPiPkg/files/2128641/boot.zip

**Comment by aiminickwong** [comment]
@andreiw   zip pkg above include whole boot part also with kernel.img :)

**Comment by aiminickwong** [comment]
@andreiw  and I used the latest RaspberryPiPkg bin file.

**Comment by aiminickwong** [comment]
@andreiw 
Hi @andreiw  I'm go on testing, and now I have a very interesting test result.
3 different result, now I show the config.txt first:
----

arm_control=0x200
enable_uart=1
armstub=RPI_EFI.fd
disable_commandline_tags=2
device_tree_address=0x8000
device_tree_end=0x10000
device_tree=bcm2710-rpi-3-b-plus.dtb

----

#### Testing1:
----
Keep kernel file named kernel.img or kernel8.img
booting...
**Result:** Rainbow screen, stoped and no logs output.

#### Testing2:
----
change kernel file name to k8
booting to shell >
input k8 then press enter.
**Result:**  Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

#### Testing3:
----
change kernel file name to k8
booting..
Press "ESC" to menu
chose "Boot Maintenace Manager" -> "Boot From File"  -> Chose "boot,[VenHw(...) /HD(1,MBR,...)]" -> chose file "k8" -> Press "Enter"
**Result:**
Success. System can boot normally and can find the efi and dmi.
PS: At Testing3 in config.txt, should set "disable_commandline_tags=2"  , if set "disable_commandline_tags=1" can not start.

----
The way to use "Boot From File" can start normally, other ways was broken.
This is really very, very, very strange. Any suggestions? I don't know too much about "Boot From File" mode. Why is this?

**Comment by andreiw** [comment]
- Testing1 is not supposed to work (it's documented in the README.md, too!) disable_commandline_tags is also documented.

To understand Testing2 and Testing3 you need to understand how the kernel EFI stub works. The kernel EFI stub unconditionally overrides the device tree command line *IFF* a command line was provided by EFI (through EFI_LOADED_IMAGE_PROTOCOL->LoadOptions, if LoadOptionsSize != 0).

- Testing2 will not work unless you provide the *whole* command line after manually invoking k8.  This is because the UEFI shell will set the command line to include the program name, so "just" invoking k8 will in effect set the command line to be "k8". You were expecting an empty command line, but that's not how it works.

- Testing3 works because the LoadOptions are NULL and LoadOptionsSize is 0 (unless you manually set it to be something else). The EFI stub then doesn't override the FDT command line, and you end up using whatever you put into cmdline.exe.

My suggestion to you - name the kernel as \efi\boot\bootaa64.efi or better yet, use a bootloader like GRUB.

**Comment by aiminickwong** [comment]
@andreiw That's great, it's very easy now. when just mv  /boot/kernel8.img  or  /boot/k8 to  /boot/efi/boot/bootaa64.efi ,  everything works now,  thanks  andreiw!
