### ISSUE TITLE
Stuck at the rainbow screen

### ISSUE THREAD

**Issue by Marekkon5** [andreiw/RaspberryPiPkg#43]
Hello.  I tried installing it on my Raspberry Pi 3. 1st try I downloaded everything latest from github and got bluescreen INACCESSIBLE BOOT DEVICE.

Second time I used exact version as on video (https://www.youtube.com/watch?v=c0VqVm8X_zQ)
And now stuck on the rainbow screen (https://lifehacker.com/what-the-raspberry-pis-rainbow-boot-screen-and-rainbow-1768470271, I have no other way to describe it)

Sorry for my noob question and thanks!

**Comment by andreiw** [comment]
Sorry, dude, you're better off asking in the big thread - https://github.com/andreiw/RaspberryPiPkg/issues/12

All I can say is that there are no circumstances under which you should be using anything older but the latest RPI_EFI.FD release.
