### ISSUE TITLE
Im newbie pls help

### ISSUE THREAD

**Issue by moltenteam** [andreiw/RaspberryPiPkg#44]
Hello, im trying to install win 10 on rpi. I have bootable USB with win 10 and i cannot boot from this USB. If I load into the setup and select boot manager then i clicked on the USB port which i plugged on win 10 usb.

**Comment by stefan2225** [comment]
You can't just boot an normal Windows 10 USB made with the media creation tool. It's for x86_64 and not arm64.

**Comment by moltenteam** [comment]
Can anybody tell me how much storage will consume the ADK on the windows host?

**Comment by moltenteam** [comment]
Can anybody provide disc image file with windows 10 arm64 installation?

**Comment by stefan2225** [comment]
You need to make one yourself with the drivers added for the RPi 3. There are some tutorials/guides on how to do this on YouTube and various other platforms.

**Comment by nikhildatta** [comment]
This is the tutorial:
https://onedrive.live.com/redir?resid=C8B0DBB75540E8D5!1187054&authkey=!AIWR8mCQAfVuGOo&ithint=file%2cdocx
Check this link for downloading win10: https://uup.rg-adguard.net/

**Comment by moltenteam** [comment]
thank you nikhildatta
