### ISSUE TITLE
Windows 10 Not Booting and Goes to BSOD (DRIVER_POWER_STATE_FAILURE)

### ISSUE THREAD

**Issue by SparrOSDeveloperTeam** [andreiw/RaspberryPiPkg#45]

**Comment by SparrOSDeveloperTeam** [comment]
Hi I am still having problems with booting Windows 10. I've been at it all this weekend. I have been able to write the install.wim to sd card, force installation of unsigned drivers, used bcdboot to make UEFI files, and I am able to get to Windows Splash. Unfortunately I keep getting a `DRIVER_POWER_STATE_FAILURE` after Windows trys booting.

![20180701_182742](https://user-images.githubusercontent.com/26008109/42140023-1ff5bcb8-7d5e-11e8-8fdc-ed2de442e082.jpg)

I am using Windows 10 Version 1703 Arm64 Home Single Language and my Raspberry Pi 3 B model. Please help.

**Comment by thchi12** [comment]
Don't plug any usb devices while booting.
BTW.....you have 1703 arm64??

**Comment by SparrOSDeveloperTeam** [comment]
Yea it required a few hours of research on the internet to get build 1703 Arm64. Also I think that solved my prob because that started the setup info.

![15304893278521251305413](https://user-images.githubusercontent.com/26008109/42140158-5dd5e0ba-7d60-11e8-80ef-7315b2e2108f.jpg)

I am not gonna close this issue yet because I feel something may happen.

**Comment by SparrOSDeveloperTeam** [comment]
Oh man I forgot about the registry hack. The file that skips setup. Well other than that I think that will be all... for now.

**Comment by SparrOSDeveloperTeam** [comment]
OMG Thank you

![15304912454081292732107](https://user-images.githubusercontent.com/26008109/42140422-cd2d8bbc-7d64-11e8-82fe-78e68ce76898.jpg)

I have waited to see this screen in a while. What I had to do was just get Windows 10 booting w/o any PnP devices connected, `regedit regfile.reg`, restart and now I am here. Thank you. Issue resolved.

**Comment by thchi12** [comment]
Could you provide the link to 1703 version? I want a try plz

**Comment by thchi12** [comment]
Ok..I want only the way ti get to that..
There're 15063.xx links on MDL's uup dump.
But all links lack edition_lang.esd and cannot be converted.

**Comment by SparrOSDeveloperTeam** [comment]
Its been a while since I've used Windows 10 on my RPi. 

> Please don’t share build links here, thanks

 I'm not.

Anyway it's been months since I've used Win10 on my Pi. It seems like a cool concept but I'm hoping we can find a way to emulate ReactOS on RPi. I feel like if we can get ReactOS running on a Raspberry Pi then it would be more stable than Windows 10.

**Comment by BenNottelling** [comment]
Really? You think ReactOS would be more stable? I don't think so ...
Is there even an arm64 build of ReactOS?

**Comment by SparrOSDeveloperTeam** [comment]
No its just ARM. I may be dreaming a little too big but I think it could be possible to port ReactOS to RPi, however idk how well it would perform. If I can't get ReactOS to work on RPi then I may end up making a Raspberry Pi image instead and get it to look and work similar to ROS.

**Comment by SparrOSDeveloperTeam** [comment]
It could work. The only problem is ReactOS has less drivers for it though so it could take longer to get it working on the Raspberry Pi. I think the Broadcom driver should work. Not sure about the RPi SDHC though. I'm mainly concerned about whether it will boot or not. I'm not currently working on the project because I'm working on a custom Windows 10 edition that installs ClassicShell and 8GadgetPack to make it feel more like Windows 7. When I am done tinkering around with Windows 10 then I'll start getting to work on ROS.

**Comment by SparrOSDeveloperTeam** [comment]
@thchi12 I now have a Repo dedicated to ReactOS on ARM [here](https://github.com/sparrdrem/rpi-roa)
