### ISSUE TITLE
Arasan debug build fails, release do build.

### ISSUE THREAD

**Issue by thchi12** [andreiw/RaspberryPiPkg#46]
Building ... /mnt/f/src/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.inf [AARCH64]
"aarch64-linux-gnu-gcc"   -g -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -ffunction-sections -fdata-sections -include AutoGen.h -fno-common -DSTRING_ARRAY_NAME=ArasanMMCHostStrings -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -mlittle-endian -mstrict-align -mgeneral-regs-only -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -fno-short-enums -fverbose-asm -funsigned-char -ffunction-sections -fdata-sections -Wno-address -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-pic -fno-pie -ffixed-x18 -O0 -mcmodel=small -DBUILD_DATE=05/09/2018 -DBUILD_COMMIT=current -c -o /mnt/f/src/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC49/AARCH64/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe/OUTPUT/./ArasanMmcHostDxe.obj -I/mnt/f/src/RaspberryPiPkg/Drivers/ArasanMmcHostDxe -I/mnt/f/src/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC49/AARCH64/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe/DEBUG -I/mnt/f/src/edk2/MdePkg -I/mnt/f/src/edk2/MdePkg/Include -I/mnt/f/src/edk2/MdePkg/Include/AArch64 -I/mnt/f/src/edk2/EmbeddedPkg -I/mnt/f/src/edk2/EmbeddedPkg/Include -I/mnt/f/src/RaspberryPiPkg -I/mnt/f/src/RaspberryPiPkg/Include /mnt/f/src/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.c
In file included from /mnt/f/src/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.h:22:0,
"aarch64-linux-gnu-gcc"   -g -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -ffunction-sections -fdata-sections -include AutoGen.h -fno-common -DSTRING_ARRAY_NAME=MmcDxeStrings -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common -mlittle-endian -mstrict-align -mgeneral-regs-only -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -fno-short-enums -fverbose-asm -funsigned-char -ffunction-sections -fdata-sections -Wno-address -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-pic -fno-pie -ffixed-x18 -O0 -mcmodel=small -DBUILD_DATE=05/09/2018 -DBUILD_COMMIT=current -c -o /mnt/f/src/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC49/AARCH64/EmbeddedPkg/Universal/MmcDxe/MmcDxe/OUTPUT/./MmcBlockIo.obj -I/mnt/f/src/edk2/EmbeddedPkg/Universal/MmcDxe -I/mnt/f/src/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC49/AARCH64/EmbeddedPkg/Universal/MmcDxe/MmcDxe/DEBUG -I/mnt/f/src/edk2/EmbeddedPkg -I/mnt/f/src/edk2/EmbeddedPkg/Include -I/mnt/f/src/edk2/MdePkg -I/mnt/f/src/edk2/MdePkg/Include -I/mnt/f/src/edk2/MdePkg/Include/AArch64 /mnt/f/src/edk2/EmbeddedPkg/Universal/MmcDxe/MmcBlockIo.c
                 from /mnt/f/src/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.c:18:
/mnt/f/src/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.c: In function ‘MMCSendCommand’:
/mnt/f/src/edk2/MdePkg/Include/Library/DebugLib.h:268:9: error: ‘MmcStatus’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         DebugPrint (PrintLevel, ##__VA_ARGS__);      \
GNUmakefile:474: recipe for target '/mnt/f/src/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC49/AARCH64/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe/OUTPUT/ArasanMmcHostDxe.obj' failed
         ^~~~~~~~~~
/mnt/f/src/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.c:293:9: note: ‘MmcStatus’ was declared here
   UINTN MmcStatus;
         ^~~~~~~~~
cc1: all warnings being treated as errors
make: *** [/mnt/f/src/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC49/AARCH64/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe/OUTPUT/ArasanMmcHostDxe.obj] Error 1

build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/f/src/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC49/AARCH64/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe]

build.py...
 : error F002: Failed to build module
        /mnt/f/src/RaspberryPiPkg/Drivers/ArasanMmcHostDxe/ArasanMmcHostDxe.inf [AARCH64, GCC49, DEBUG]

- Failed -
Build end time: 15:55:02, Jul.02 2018
Build total time: 00:05:00

**Comment by andreiw** [comment]
Thanks. Fixed.
