### ISSUE TITLE
Windows wont run

### ISSUE THREAD

**Issue by ham1255** [andreiw/RaspberryPiPkg#49]
So get error that need reg file so i done it then windows did crAsh then reboot then getting bad state error even there no usb plugged in

**Comment by ham1255** [comment]
Then i try did all steps again then new error show up 
Windows setup could bot configer windows to run on this computer

**Comment by thchi12** [comment]
You don't need the reg hack
Making your FAT partition active solves the setup error.

**Comment by ham1255** [comment]
Making alll partitions as fat?

**Comment by thchi12** [comment]
No..
You've made two partitions. Just make the partition which has boot files active. （ It should be a FAT16 or FAT32 partition. ）

**Comment by thchi12** [comment]
Then make the fat32 partition active.

**Comment by ham1255** [comment]
Is there sound drivers yet?

**Comment by driver1998** [comment]
We do, checkout github.com/driver1998/bsp if you haven’t know yet.

发送自我的 Windows 10 手机

________________________________
发件人: mohammed jassim alajel <notifications@github.com>
发送时间: Friday, July 20, 2018 7:43:38 AM
收件人: andreiw/RaspberryPiPkg
抄送: Subscribed
主题: Re: [andreiw/RaspberryPiPkg] Windows wont run (#49)


Is there sound drivers yet?

―

**Comment by ham1255** [comment]
@driver1998 is there ethernet driver too?

**Comment by andreiw** [comment]
Not a uefi issue. Use issue 12 instead

**Comment by andreiw** [comment]
https://github.com/andreiw/RaspberryPiPkg/issues/12
