### ISSUE TITLE
DwUsbHostDxe: unmaintainable spaghetti code

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#5]
This driver is a mess, needs refactoring.

**Comment by alexfru** [comment]
Dunno if you're aware, but there's this book: [USB: The Universal Serial Bus](http://www.fysnet.net/the_universal_serial_bus.htm) by Benjamin David Lunt. Might be helpful unless you already have it (3rd ed just came out). And Ben may be able to answer some of your questions.

**Comment by andreiw** [comment]
Thanks, Alex!

**Comment by hansmbakker** [comment]
Is this issue still an issue with the new usb driver?

**Comment by andreiw** [comment]
There is no new driver in UEFI.

A

**Comment by andreiw** [comment]
It got better so might as well close. Anyway, further development will happen over at https://github.com/tianocore/edk2-platforms/tree/master/Platform/RaspberryPi/RPi3 only
