### ISSUE TITLE
Cannot boot on USB hard disk

### ISSUE THREAD

**Issue by zengge2** [andreiw/RaspberryPiPkg#51]
I made a FAT32 partition and an NTFS partition in USB hard disk, and then I placed UEFI files in FAT32 partition and flashed Windows 10 ARM64 to NTFS partition,and I also made EFI boot on FAT32 partition. When I plugged hard disk to rpi 3b+ and powered it on, I got a rainbow screen and it won't boot. How can I deal with this problem?

**Comment by andreiw** [comment]
Please share the exact partition layout, and contents. Note: Pi cannot boot from a GPT disk.

A

**Comment by zengge2** [comment]
BTW, is there a compatible USB mouse and keyboard driver for 3b+? I cannot operate it when I entered Windows 10 Setup UI.

**Comment by mariobalanica** [comment]
[dwusb.zip](https://github.com/andreiw/RaspberryPiPkg/files/2216875/dwusb.zip)

**Comment by zengge2** [comment]
@mariobalanica Your driver files caused 3b+ a BSoD : PAGE_FAULT_IN_NONPAGED_AREA.

**Comment by andreiw** [comment]
Not a uefi issue

https://github.com/andreiw/RaspberryPiPkg/issues/12
