### ISSUE TITLE
SMBIOS tables should only be using RTS data

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#53]
Validate that no BS data is referenced by SMBIOS tables.

@driver1998 noticed that a few of the strings were empty when seen from Windows. To be investigated.

**Comment by andreiw** [comment]
@driver1998 do you remember which strings were not working? is it once in a while or always?

**Comment by driver1998** [comment]
If you check that registery key I mentioned at that time, you'll see that the whole key is empty. There are offical MS docs about that key.

**Comment by driver1998** [comment]
That is HKLM\Hardware\Description\BIOS

**Comment by driver1998** [comment]
MS docs about this
http://download.microsoft.com/download/5/D/6/5D6EAF2B-7DDF-476B-93DC-7CF0072878E6/SMBIOS.doc
It is old, but I think it doesn't really changed, as both the MS UEFI for PI and the UEFI of my Lenovo laptop all have correct values there.

**Comment by driver1998** [comment]
Well the key is apparently HKLM\Hardware\Description\System\BIOS now, I don't have a Windows machine nearby to check though.
It is used by Windows and some application to get the SKU and model number of the machine.

**Comment by andreiw** [comment]
Yes, I found the key and it is empty.

Is this a regression? i.e. has it ever worked in this firmware?

**Comment by andreiw** [comment]
![img_0286](https://user-images.githubusercontent.com/732523/45530458-bf879780-b7b8-11e8-9fcf-8386c1a39511.JPG)

I have a fix. It was a regression :(. Will update binaries today.

**Comment by andreiw** [comment]
Fixed in https://github.com/andreiw/RaspberryPiPkg/tree/master/Binary/prebuilt/2018Sep14-GCC5
