### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by Admin-Account** [andreiw/RaspberryPiPkg#55]
A lot of people have encountered this problem."Exiting uefi and booting os kernel",And with the Windows blue logo and the rotating white ball.Under the"Exiting uefi and booting os kernel"There are also green strips.Can you tell me what to do? thank you very much! @andreiw

**Comment by thchi12** [comment]
Well it's expected behavior. Just wait and Windows will start up. Remember to disconnect any USB devices  before you see the desktop.
