### ISSUE TITLE
Connecting my wireless keyboard causes the UEFI to freeze

### ISSUE THREAD

**Issue by BenNottelling** [andreiw/RaspberryPiPkg#57]
I bought a mini wireless keyboard with a trackpad because I thought it would go nice with my raspberry pi and it works great with windows 10, but it causes the UEFI to freeze so I have to unplug it during the boot and plug it back in once windows is up which is somewhat inconvenient

**Comment by andreiw** [comment]
There are plenty of keyboards that do, in fact, work, so it would be helpful to know the exact model.

Additionally, if you have a UART connection to the Pi, please boot the DEBUG build and give me the serial output when UEFI is booted with the affected keyboard.

**Comment by BenNottelling** [comment]
Sorry, I guess my comment wasn't very helpful. Either way it's a cheapo keyboard. An `inland 71113`.
Searching it on google actually shows two different mice, but it's this one:
https://express.google.com/product/Inland-2-4G-Wireless-Mini-Keyboard-Black-71113/3899007861794273641_2623038281648033392_6136318
I don't have a UART connection to the Pi though. (I'm actually not sure what that is)

**Comment by mariobalanica** [comment]
Even if you can boot the UEFI firmware with the keyboard plugged in, you still have to unplug it from the USB ports during the boot process (otherwise Windows will most likely throw a BSoD).

**Comment by BenNottelling** [comment]
It boots if I plug it in after the UEFI, but if it's plugged in during the UEFI jt just sits there frozen until I unplug it at which point it continues as usual

**Comment by mariobalanica** [comment]
You need something like this: https://www.ebay.com/bhp/usb-ttl to get the serial output from the Pi.

**Comment by andreiw** [comment]
@BenNottelling https://elinux.org/RPi_Serial_Connection

**Comment by andreiw** [comment]
No promises, but I'll try to get one, as it seems like a genuinely useful wireless USB keyboard to have. These kinds of bugs are notoriously difficult to track down and fix, and having zero documentation about the USB host controller really doesn't help.

**Comment by BenNottelling** [comment]
Sounds good! It's actually decently nice, I'm happy with it. I wouldn't be surprised if it uses pretty generic hardware so I wouldn't be surprised if fixing it would allow other keyboards to work. If you decide not to get one let me know and I'll buy one of the USB-TTL devices that Mario linked and give you the serial output.

**Comment by andreiw** [comment]
I’ve been really hoping I fixed all USB keyboard issues. You’re the first person with a reported regression in half a year :)).

**Comment by BenNottelling** [comment]
Sounds like you got pretty close, thanks for helping by the way :)

**Comment by BenNottelling** [comment]
Hey @andreiw just checking in to see if you decided to buy the keyboard or not. Thanks for any help! :)

**Comment by andreiw** [comment]
@BenNottelling I got an Inland K01X1 just today. Damn, I got the wrong one! But the good news is that this one works just fine (tested with 3B+).

I'll buy this other one, too - the inland one you have. I really like the K01X1. I don't think I ever was so excited about a keyboard since the Model M.

![img_2050](https://user-images.githubusercontent.com/732523/46651069-d4afd600-cb6c-11e8-977e-266abedd14e9.JPG)
![img_2620](https://user-images.githubusercontent.com/732523/46651073-d7aac680-cb6c-11e8-9892-ee20bc048248.JPG)

**Comment by BenNottelling** [comment]
@andreiw  Didn't I link one? 😁
I'm glad you like it though! That way it wasn't a waste 😊

**Comment by andreiw** [comment]
Okay I am still confused. The link you have links to something that looks like a controller - https://express.google.com/product/Inland-2-4G-Wireless-Mini-Keyboard-Black-71113/3899007861794273641_2623038281648033392_6136318. 

I bought one as the Inland IK80, and it works.

And Inland 71113 search, though, leads me to https://www.amazon.com/Inland-Smart-Keyboard-Remote-71113/dp/B01MXHRJH2, which looks exactly like the IK110 I got. Sigh.

At this point I have two Inland keyboards and they both work. Sorry, I don't think I'm going to go buy another one :(. I guess you can buy one of these. I am guessing the 71113 is an older version of the IK110.

![image](https://user-images.githubusercontent.com/732523/46852864-6700e580-cdca-11e8-89f7-81b45424ba22.png)
