### ISSUE TITLE
UNACCESSABLE_BOOT_DEVICE error while starting

### ISSUE THREAD

**Issue by moltenteam** [andreiw/RaspberryPiPkg#59]
Hi,
i'm getting a problem with BSOD. I did all mentioned in tutorial from Davindra - DIY King. I successfully injected drivers from andreiw's github repository called rpi3winstuff.

Please help.

**Comment by moltenteam** [comment]
Now, i successfully injected WoA drivers from this repository. I'm getting another error: DRIVER_POWER_STATE_FAILURE. I think it must be my AiO Microsoft Keyboard. If I touch any key on my keyboard during start Windows freezes. Any ideas??

**Comment by stefan2225** [comment]
You have to boot without USB Devices plugged in.

**Comment by andreiw** [comment]
not an UEFI issue
