### ISSUE TITLE
DwUsbHostDxe: reconnect -r breaks USB

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#6]
No USB enumeration happening after reconnect -r. No port state change, nada.

**Comment by andreiw** [comment]
This is caused by the DwUsbHostDxe not implementing the driver binding protocol.

**Comment by novaspirit** [comment]
is this a uefi issue or driver issue? info i found on binding protocol http://wiki.phoenix.com/wiki/index.php/EFI_DRIVER_BINDING_PROTOCOL

**Comment by andreiw** [comment]
It’s a UEFI driver implementation issue that doesn’t affect normal operation (or OS support)

A
