### ISSUE TITLE
Route PL011 UART to GPIOs 32 and 33 for Bluetooth

### ISSUE THREAD

**Issue by Googulator** [andreiw/RaspberryPiPkg#61]
Currently GPIOs 32 and 33 are left in their default configuration, which is likely GPIO input. These pins are used on the Pi 3 to interface with the Bluetooth controller. To route the correct UART signals to them, they need to be configured as ALT3.

Additionally, GPIOs 30 and 31 appear to be used for Bluetooth PCM audio, requiring an ALT2 configuration.

**Comment by andreiw** [comment]
Good idea, thanks, will expose this through chipset config and make it the default configuration.

**Comment by andreiw** [comment]
@Googulator can you confirm if these routings are the same across Pi3 and Pi3B+?

**Comment by Googulator** [comment]
Yes, it's the same on all Pis equipped with Bluetooth. Probably even on the Zero W.

**Comment by Googulator** [comment]
BTW, why are you always rebasing the README on top? Makes it hard to see at a glance when the repo changes.
