### ISSUE TITLE
Can't Acess (Maybe because corporate network)

### ISSUE THREAD

**Issue by EdenHubs12** [andreiw/RaspberryPiPkg#65]
For some reason, I can not access the website for the downloads.
Does anyone know why this is?

![crop](https://user-images.githubusercontent.com/35420387/45531548-d4991080-b822-11e8-97e8-8c6c7eb635df.png)

**Comment by andreiw** [comment]
@mariobalanica?

[ my guess is yes, probably some middleware on your end, try a different location to download from ]

**Comment by mariobalanica** [comment]
You can try disabling TLS 1.3 support from `chrome://flags/#tls13-variant` .

**Comment by andreiw** [comment]
Not a UEFI issue
