### ISSUE TITLE
uup iso creator 

### ISSUE THREAD

**Issue by GlowingObsidian** [andreiw/RaspberryPiPkg#66]
I always get this error at the end: 
Creating install.wim . . .
============================================================================

[ERROR] "\Windows\WinSxS\arm64_microsoft-windows-s..english-autocorrect_31bf3856ad364e35_10.0.17134.1_none_c2efc9a4127a9b2b\MsSp7en-US.acl": blob not found
        SHA-1 message digest of missing blob:
        2e014fdf82a63baf46bfcf15baa9f3d2a6b21d1d
ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.
ERROR: Exiting with error code 55:
       A file resource needed to complete the operation was missing from the WIM.

any ideas what's the problem and solution ? I am using build 17134 for arm64

**Comment by andreiw** [comment]
Nope. This is not a firmware issue. Feel free to ask in the big MEGA Windows thread and see if someone helps.
