### ISSUE TITLE
Duplicate code DwUsbHostDxe

### ISSUE THREAD

**Issue by mrmajik45** [andreiw/RaspberryPiPkg#69]
Found in:
Drivers\DwUsbHostDxe\DwUsbHostDxe.c:684-693
Drivers\DwUsbHostDxe\DwUsbHostDxe.c:737-746

**Comment by andreiw** [comment]
It's similar, and some places may be questionable (EfiUsbPortReset for example), but it's not duplicate. One sets features. Another clears. I'm closing this as a not a bug at the moment although cleanup may be desired at some point.
