### ISSUE TITLE
BSoD in boot WoA: NTFS_FILE_SYSTEM

### ISSUE THREAD

**Issue by Andryshik345** [andreiw/RaspberryPiPkg#73]
Hello, I'm trying to boot WoA with UEFI on SD card and Windows installed on USB device. But I'm get an BSoD with stop code NTFS_FILE_SYSTEM. This is problem with dwusb or something else?
SD card have 2 GB memory, FAT32 filesystem with debug UEFI in root and Windows 17134.1.180410-1804.RS4 flashed on USB with Windows on Raspberry imager.

Two screenshots is here: https://imgur.com/a/qzcvH51

**Comment by mariobalanica** [comment]
You can't boot Windows from an USB drive at the moment. The USB driver is very unstable.

**Comment by Andryshik345** [comment]
@mariobalanica 
Oh, okay, then i close this thread, thanks for answer.
