### ISSUE TITLE
Keyboard and Mouse not working

### ISSUE THREAD

**Issue by AsumYT** [andreiw/RaspberryPiPkg#81]
Hey, i have a problem with the Windows 10 WoA for the Raspberry Pi 3b. When i start the Windows 10, it works fine. But when i connect a Mouse or a Keyboard, i can't do anything with it. How i can fix it?

Regards,

PS: Sorry for bad English

**Comment by andreiw** [comment]
Also, not a UEFI issue (although the UEFI USB driver also has...issues... just not as many as the WoA one :-)).
