### ISSUE TITLE
HypDxe: allow trapping VC mailbox access

### ISSUE THREAD

**Issue by andreiw** [andreiw/RaspberryPiPkg#84]
This will allow both tracing OS access to VC firmware (i.e. clock control, etc) and interposing (e.g. declare less RAM, etc).

May be useful to diagnose further issues like https://github.com/andreiw/RaspberryPiPkg/issues/83

**Comment by driver1998** [comment]
It may also be useful to diagnose the issue that ACT LED keeps blinking (in a pattern that is usually seen when the Pi is "turned off") when RPIQ driver is loaded in WoA.
In IoT Core, that LED stays off when completely booted.

**Comment by andreiw** [comment]
Interesting. Sure.

A
