### ISSUE TITLE
Installing unRAID on UEFI (Possible?)

### ISSUE THREAD

**Issue by moltenteam** [andreiw/RaspberryPiPkg#86]

**Comment by BenNottelling** [comment]
unRAID isn't available on ARM64 which is what the raspberry PI uses, but you may be able to find an ARM64 alternative

**Comment by moltenteam** [comment]
Hello,
I was trying to install unRAID (unraid.net) onto Raspberry Pi 3 Model B with this UEFI. (unRAID is a Linux based OS) I normally imaged unRAID with unRAID USB Creator, enabled Allow UEFI Boot. When I booted to UEFI, it launched UEFI Interactive Shell. I typed in bootx64.efi (the unRAID UEFI bootloader) and it said Unsupported. Is even possible to install unRAID to RPi 3?

Thanks for any replies and sorry for my bad english.

**Comment by moltenteam** [comment]
Thank you, I'll try it.

**Comment by moltenteam** [comment]
OK, my plan is now to install qemu onto raspbian then emulate unRAID. Thank you for your help, BenNotteling.

**Comment by andreiw** [comment]
You're trying to run a 64-bit x86 bootloader (bootx64) instead of a 64-bit Arm one (bootaa64)

Your plan shouldn't be trying to emulate unRAID. That would be awful. You need to rebuild unRAID for Arm.

**Comment by moltenteam** [comment]
Oh, thank you @andreiw
