### ISSUE TITLE
Error AARCH64 small code model requires identical ELF and PE/COFF section offsets modulo 4 KB.

### ISSUE THREAD

**Issue by XperfectTR** [andreiw/RaspberryPiPkg#9]
WriteSections64(): /root/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC5/AARCH64/RaspberryPiPkg/AcpiTables/AcpiTables/OUTPUT/./APIC.dll AARCH64 small code model requires identical ELF and PE/COFF section offsets modulo 4 KB.
GenFw: ERROR 3000: Invalid
  WriteSections64(): /root/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC5/AARCH64/RaspberryPiPkg/AcpiTables/AcpiTables/OUTPUT/./APIC.dll AARCH64 small code model requires identical ELF and PE/COFF section offsets modulo 4 KB.
make: *** [/root/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC5/AARCH64/RaspberryPiPkg/AcpiTables/AcpiTables/OUTPUT/APIC.acpi] Error 2
GNUmakefile:344: recipe for target '/root/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC5/AARCH64/RaspberryPiPkg/AcpiTables/AcpiTables/OUTPUT/APIC.acpi' failed

build.py...
 : error 7000: Failed to execute command
        make tbuild [/root/Build/RaspberryPiPkg-AARCH64/DEBUG_GCC5/AARCH64/RaspberryPiPkg/AcpiTables/AcpiTables]

build.py...
 : error F002: Failed to build module
        /root/RaspberryPiPkg/AcpiTables/AcpiTables.inf [AARCH64, GCC5, DEBUG]

- Failed -
Build end time: 16:17:10, Apr.02 2018
Build total time: 00:00:12

**Comment by andreiw** [comment]
Thanks for the report.

Did you apply edk2Patches/0003-BaseTools-tools_def-support-ASLC-files-on-AArch64.patch?

**Comment by andreiw** [comment]
I just downloaded the Linaro GCC5 tools and validated that stuff builds. Here's a sample build script. You're welcome.

export WORKSPACE=$PWD
export PACKAGES_PATH=$WORKSPACE/edk2:$WORKSPACE/RaspberryPiPkg
export EDK_TOOLS_PATH=$WORKSPACE/edk2/BaseTools
export PATH=$PATH:$PWD/gcc-linaro-5.5.0-2017.10-i686_aarch64-linux-gnu/bin-
export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-

make -C $EDK_TOOLS_PATH
echo $EDK_TOOLS_PATH
. $WORKSPACE/edk2/edksetup.sh BaseTools

build -b DEBUG -a AARCH64 -t GCC5 -p RaspberryPiPkg/RaspberryPiPkg.dsc
build -b RELEASE -a AARCH64 -t GCC5 -p RaspberryPiPkg/RaspberryPiPkg.dsc

**Comment by XperfectTR** [comment]
Thank you. I did not notice the patch.
