### ISSUE TITLE
Is it posible to fix?

### ISSUE THREAD

**Issue by SlavicGopnikOnThePI** [andreiw/RaspberryPiPkg#90]
I have a problem with keyboard not working at all!
I open task manager it says device driver isnt installed,i cant find a way to install it!

Any help would be appreciated!

**Comment by andreiw** [comment]
Sorry dude, I know these USB issues are painful for you and for everyone involved. It's not a firmware issue though...

Maybe one of these days I'll have time to dedicate to working on an NT driver...
