### ISSUE TITLE
Error booting to Windows

### ISSUE THREAD

**Issue by ThatsFluke** [andreiw/RaspberryPiPkg#92]
Hey, when I boot to Windows 10 on my RPI3 B+ I got a blue screen ( Inaccessible Boot Device ) and it would restart. Everytime it would restart it goes through the UEFI Bios, etc then loads Windows and pops up with the error again. Could you try help resolve this problem? Thanks!

**Comment by thchi12** [comment]
this means you didn't inject your drivers properly.

**Comment by BenNottelling** [comment]
When I used WOR the other
