### ISSUE TITLE
RedHat Enterprise Linux Server (RHEL) install

### ISSUE THREAD

**Issue by moltenteam** [andreiw/RaspberryPiPkg#93]
Hello, is it possible to install RHEL with this UEFI? I know Redhat OSes are available for x86_64, but there is also ARM version for developers. I want to use their RedHat KVM Virtualization Hypervisor to provision my hardware resources for VMs. Thanks for any replies

**Comment by andreiw** [comment]
You can run 64-bit Linux distros with Pi support.

RHEL is very pedantic and will only work on systems that are fully SBSA and SBBR compliant. The Pi is neither, minimally because of its weird interrupt controller.

Fedora should.

A

**Comment by moltenteam** [comment]
I tried Fedora Workstation 29 for RPi, but it was very slow and unstable.

I will run RHEL on Udoo x86 for provisioning.
