### ISSUE TITLE
Third party drivers compatible with windows 10 arm 64

### ISSUE THREAD

**Issue by siddhantisro** [andreiw/RaspberryPiPkg#95]
Hi,

I have successfully installed windows 10 ARM 64 on raspberry pi 3 and my windows is running fine with some issues regarding the Keyboard and mouse control which is lost frequently. My main aim is to install a third party driver for a DVB-S2 USB TV Tuner which is compatible with normal windows but when i try to install it in windows 10 ARM 64 running on my raspberry pi it pops up a error saying 'This app can't run on your PC' . Is there any possible way to run a driver compatible with normal windows to make it run on windows 10 ARM 64.

**Comment by thchi12** [comment]
You need those drivers in arm64.
Normal drivers don't work.
