### ISSUE TITLE
Rpi won't boot

### ISSUE THREAD

**Issue by ExtremeDudeEver** [andreiw/RaspberryPiPkg#99]
After imaging windows on a 32 GB Sandisk ultra sd card rpi no longer boots
Can I know what is the issue is it a unsupported sd card or ?

I imaged it with woa software tool

**Comment by BenNottelling** [comment]
You mean WOR not WOA?

**Comment by andreiw** [comment]
There are multiple “gradations” of won’t boot, so it would be helpful to be specific about what you are seeing (or not seeing, compared to a card you know works well)

A

**Comment by andreiw** [comment]
No feedback, so closing
